version: '3'

services:
  db:
      build:
          context: ./db
          dockerfile: Dockerfile
      restart: always
      environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
      ports:
          - 5432:5432

  adminer:
      image: adminer
      restart: always
      ports:
          - 8080:8080

  web:
    build: ./app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db